[tool.bumpver]
current_version = "1.1.11"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"'
]
"src/zendron/__init__.py" = ["{version}"]

[tool.setuptools.package-data]
zendron = [
    "conf/__init__.py",
    "conf/default_template.yaml",
    "conf/config_template.yaml",
    "pods/dendron.markdown/config.import.yml"
]