[tool.bumpver]
current_version = "1.0.19"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"'
]
"src/zendron/__init__.py" = ["{version}"]

"README.md" = [
    "Version: {version}"
]
