# conf/zendron/default.yaml
defaults:
- _self_
remove: false
initialized: true
hydra_logging:
  loggers:
    logging_example:
      level: INFO
hydra:
  run:
    dir: ''
  output_subdir: null

# zendron - default
zotero_comment_title: zendron comment
pod_path: zendron_pod
dendron_limb: zendron.import
