defaults:
  - default
  - _self_
library_id : 4932332 # STARTER CONFIG
library_type : group # [group, user] # STARTER CONFIG
api_key : FoC1uOvsMnNdYmpYuY5JpETw # STARTER CONFIG
collection: null # null for entire library
item_types: [journalArticle, book, preprint, conferencePaper, report]
local_image_path: /Users/<username>/Zotero/cache # STARTER CONFIG
dendron_limb: zendron.import
zotero_comment_title: zendron comment
pod_path: zotero_pod